sudo: required
services:
  # automatically install docker in our container
  - docker

before_install:
  - docker build -f Dockerfile.dev -t tuandl/docker-react .

script:
  - docker run -e CI=true tuandl/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  # region beanstalk created
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  # S3 bucket 
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
