version: '3'
services:
  react-app:
    build:
      # where to look up
      context: .
      # the docker with the name
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  react-test:
    build:
      # where to look up
      context: .
      # the docker with the name
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]